name: Storybook cleanup 🧹

# Note: This event will only trigger a workflow run if the workflow file is on the default branch.
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#delete
on: [delete]

permissions:
  contents: write

env:
  GH_PAGES_BRANCH: docs
  GH_PAGES_FOLDER: docs
  CATALOG_FILE: docs/catalog.json

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.GH_PAGES_BRANCH }}
      - name: "Remove a bundle directory"
        run: rm -rf "${GH_PAGES_FOLDER}/${{ github.ref }}"
      - uses: boonya/gh-actions@main
        with:
          catalog: ${{ env.CATALOG_FILE }}
          remove: true
      - name: "Publish changes"
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: ${{ env.GH_PAGES_BRANCH }}
          folder: ${{ env.GH_PAGES_FOLDER }}
          target-folder: ${{ env.GH_PAGES_FOLDER }}
